name: My Custom Action

on:
  push:
    branches:
      - main  # Runs the action on push to the 'main' branch
  schedule:
    - cron: "0 12 * * *"  # Runs at 12:00 UTC every day
  workflow_dispatch:  # Allows manual triggering from the GitHub interface

jobs:
  my-job:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu machine
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Include your email in the step name as required
      - name: '21f3002580@ds.study.iitm.ac.in'  # Enclose the email address in quotes
        run: echo "Hello, world! This is the email: 21f3002580@ds.study.iitm.ac.in"

      # Step 3: Commit and push changes (example step)
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Automated update" || exit 0
          git push
